export default {
  products: [
    {
      _id: '111111111111111111111111',
      name: 'Hiskywin Full Zip Running Shirts Thermal Workout',
      category: 'Shirts',
      image: '/images/product-1.jpg',
      price: 59,
      brand: 'Hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Nike Full-Zip Hoodie Mens Workout Sweatshirt',
      category: 'Shirts',
      image: '/images/product-2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 5,
      numReviews: 51,
    },
    {
      _id: '3',
      name: 'Adidas Mens Long Sleeve Hoodie',
      category: 'Shirts',
      image: '/images/product-3.jpg',
      price: 59,
      brand: 'Adidas',
      rating: 4,
      numReviews: 45,
    },
    {
      _id: '4',
      name: 'Under Armour Mens Sportstyle Tricot Joggers',
      category: 'Pants',
      image: '/images/product-4.jpg',
      price: 90,
      brand: 'Under Armour',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Champion Mens Graphic Powerblend Fleece Jogger',
      category: 'Pants',
      image: '/images/product-5.jpg',
      price: 119,
      brand: 'Champion',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
      category: 'Pants',
      image: '/images/product-6.jpg',
      price: 85,
      brand: 'Aelfric Eden',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
    {
      _id: '8',
      name: 'jackets long multi-pocket',
      category: 'pants',
      image: '/images/product-8.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
    },
    {
      _id: '9',
      name: 'jackets long multi-pocket',
      category: 'pants',
      image: '/images/product-9.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
    },
    {
      _id: '10',
      name: 'jackets long multi-pocket',
      category: 'pants',
      image: '/images/product-10.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
    },
    {
      _id: '11',
      name: 'jackets long multi-pocket',
      category: 'pants',
      image: '/images/product-11.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
    },
    {
      _id: '12',
      name: 'jackets long multi-pocket',
      category: 'pants',
      image: '/images/product-12.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
    },
    {
      _id: '13',
      name: 'jackets long multi-pocket',
      category: 'pants',
      image: '/images/product-13.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
    },
    {
      _id: '14',
      name: 't shirt',
      category: 'shirts',
      image: '/images/product-14.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
    },
    {
      _id: '15',
      name: 't shirt',
      category: 'shirts',
      image: '/images/product-15.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
    },
    {
      _id: '16',
      name: 't shirt',
      category: 'shirts',
      image: '/images/product-16.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
    },
    {
      _id: '17',
      name: 't shirt',
      category: 'shirts',
      image: '/images/product-17.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
    },
    {
      _id: '18',
      name: 't shirt',
      category: 'shirts',
      image: '/images/product-18.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
    },
    {
      _id: '19',
      name: 'shoes',
      category: 'shoes',
      image: '/images/product-19.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
    },
    {
      _id: '20',
      name: 'shoes',
      category: 'shoes',
      image: '/images/product-20.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
    },
    {
      _id: '21',
      name: 'shoes',
      category: 'shoes',
      image: '/images/product-21.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
    },
  {
    _id: '22',
      name: 'shoes',
      category: 'shoes',
      image: '/images/product-22.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
  },
  {
    _id: '23',
      name: 'shoes',
      category: 'shoes',
      image: '/images/product-23.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
  },
  {
    _id: '24',
      name: 'shoes',
      category: 'shoes',
      image: '/images/product-24.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
  },
  {
    _id: '25',
      name: 'shoes',
      category: 'shoes',
      image: '/images/product-25.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
  },
  {
    _id: '26',
      name: 'shoes',
      category: 'shoes',
      image: '/images/product-26.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
  },
  {
    _id: '27',
      name: 'shoes',
      category: 'shoes',
      image: '/images/product-27.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
  },
  {
    _id: '28',
      name: 'shoes',
      category: 'shoes',
      image: '/images/product-28.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
  },
  {
    _id: '29',
      name: 'shoes',
      category: 'shoes',
      image: '/images/product-29.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
  },
  {
    _id: '30',
      name: 'shoes',
      category: 'shoes',
      image: '/images/product-30.jpg',
      price: 300,
      brand: 'Levis',
      rating: 4.2,
      numReviews: 30,
      countInStock: 5,
  },
  ],
};
